// constants

// for user
export const INCREMENT_AMOUNT_BY_1="INCREMENT_AMOUNT_BY_1";
export const DECREMENT_AMOUNT_BY_1="DECREMENT_AMOUNT_BY_1";
export const INCREMENT_AMOUNT_BY_VALUE="INCREMENT_AMOUNT_BY_VALUE";
export const DECREMENT_AMOUNT_BY_VALUE="DECREMENT_AMOUNT_BY_VALUE";
export const INITLIZE_USER="INITLIZE_USER";

// for blog
export const INITLIZE_BLOG="INITLIZE_BLOG";
export const INCREMENT_BLOG_LENGTH_BY_1="INCREMENT_BLOG_LENGTH_BY_1";
export const DECREMENT_BLOG_LENGTH_BY_1="DECREMENT_BLOG_LENGTH_BY_1";
export const INCREMENT_BLOG_LENGTH_BY_VALUE="INCREMENT_BLOG_LENGTH_BY_VALUE";
export const DECREMENT_BLOG_LENGTH_BY_VALUE="DECREMENT_BLOG_LENGTH_BY_VALUE";